### 1 Load the data and extract a subset as input

Text2emotion processes the data and yield the emotion of the sentence from these 5 emotions (Happy, Angry, Sad, Surprise, and Fear)

In [1]:
import pandas as pd

In [2]:
# Replace 'your_file.csv' with the path to your CSV file
file_path = '.\Source\GoEmotions_1000_Clean.csv'
# Load the data
raw_df = pd.read_csv(file_path)
sub_df=raw_df[raw_df['primary_emotion'].isin(['joy', 'surprise', 'anger', 'fear', 'sadness', 'neutral'] )]

In [3]:
display(sub_df)

,id,text,anger,fear,sadness,disgust,nervousness,joy,surprise,desire,excitement,neutral,primary_emotion,clean_text
0,1,Don't attend. Don't engage. They want validati...,1,0,0,0,0,0,0,0,0,0,anger,attend engage want validation give
1,2,I can guarantee you for many the hate for this...,1,0,0,1,0,0,0,0,0,0,anger,guarantee many hate administration started muc...
2,3,that was such a misstep from their PR. wtf wer...,1,0,0,0,0,0,0,0,0,0,anger,misstep pr wtf thinking people expecting publi...
3,4,Don’t insult our users. You’re done here — you...,1,0,0,0,0,0,0,0,0,0,anger,insult users done alt
4,5,[NAME] was only president for four years dumba...,1,0,0,0,0,0,0,0,0,0,anger,name president four years dumbass name served ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Well she ran with a bunch of soldiers before a...,0,0,0,0,0,0,0,0,0,1,neutral,well ran bunch soldiers anf would imagine colo...
996,997,Not if the Pats are 4-12 that season.,0,0,0,0,0,0,0,0,0,1,neutral,pats season
997,998,That's how I feel every time someone wants me ...,0,0,0,0,0,0,0,0,0,1,neutral,feel every time someone wants hold baby
998,999,But little [NAME] might grow up to be one of t...,0,0,0,0,0,0,0,0,0,1,neutral,little name might grow one
999,1000,My fans on patreon will be rewarded soon,0,0,0,0,0,0,0,0,0,1,neutral,fans patreon rewarded soon

### 2  Loop the 600 samples to get emotion

In [4]:

# !pip install text2emotion
# !pip uninstall emoji
# !pip install emoji==1.7
# https://github.com/aman2656/text2emotion-library/issues/10

In [5]:
import text2emotion as te

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [6]:
#igore trust 
emotions_list = ['Happy', 'Angry', 'Surprise', 'Sad', 'Fear']  # 'neutral',    
em_df = pd.DataFrame(columns=emotions_list+["id"])
display(em_df)

Empty DataFrame
Columns: [Happy, Angry, Surprise, Sad, Fear, id]
Index: []

In [7]:
len(sub_df)

600

In [8]:
for  index, row in sub_df.iterrows():
    sentence=row["clean_text"]
    scores =te.get_emotion(sentence)  
    # print(scores)  #e.g. {'Happy': 0.5, 'Angry': 0.0, 'Surprise': 0.0, 'Sad': 0.5, 'Fear': 0.0}
    # Create a row with the scores for the specified emotions and 0 for the rest
    em = {emotion: scores.get(emotion, 0) for emotion in emotions_list}
    em['id'] = row['id']
    # Convert the row dictionary to a DataFrame and concatenate with the existing DataFrame
    em_df = pd.concat([em_df, pd.DataFrame([em])], ignore_index=True)

C:\Users\asus\AppData\Local\Temp\ipykernel_2920\2321569494.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  em_df = pd.concat([em_df, pd.DataFrame([em])], ignore_index=True)

In [9]:
len(em_df)

600

In [10]:
#if  all 0 for ''Happy', 'Angry', 'Surprise', 'Sad', 'Fear' , then neutral
em_df['neutral'] = em_df.apply(lambda row: 1 if all(row[:5] == 0) else 0, axis=1)
em_df=em_df[['Happy', 'Angry', 'Surprise', 'Sad', 'Fear','neutral','id']]
#Rename columns: align  emotions from text2emotion with   primary_emotion from sample
em_df.rename(columns={'Happy': 'joy', 'Angry': 'anger', 'Surprise': 'surprise', 'Sad': 'sadness', 'Fear': 'fear' }, inplace=True)

In [11]:
display(em_df)

     joy  anger  surprise  sadness  fear  neutral    id
0    0.0    0.0       0.0      0.0   1.0        0     1
1    0.0    0.0       0.0      1.0   0.0        0     2
2    0.5    0.0       0.0      0.5   0.0        0     3
3    0.0    0.0       0.0      0.0   0.0        1     4
4    0.0    0.0       0.0      1.0   0.0        0     5
..   ...    ...       ...      ...   ...      ...   ...
595  0.0    0.0       0.5      0.0   0.5        0   996
596  0.0    0.0       0.0      0.0   0.0        1   997
597  0.0    0.0       0.0      0.0   0.0        1   998
598  0.0    0.0       0.0      0.0   0.0        1   999
599  0.0    0.0       0.0      0.0   0.0        1  1000

[600 rows x 7 columns]

In [12]:
sel_col=["id","clean_text","primary_emotion"]
t2e_result_df  = pd.merge(sub_df[sel_col], em_df, on='id', how='inner')
display(t2e_result_df)

,id,clean_text,primary_emotion,joy,anger,surprise,sadness,fear,neutral
0,1,attend engage want validation give,anger,0.0,0.0,0.0,0.0,1.0,0
1,2,guarantee many hate administration started muc...,anger,0.0,0.0,0.0,1.0,0.0,0
2,3,misstep pr wtf thinking people expecting publi...,anger,0.5,0.0,0.0,0.5,0.0,0
3,4,insult users done alt,anger,0.0,0.0,0.0,0.0,0.0,1
4,5,name president four years dumbass name served ...,anger,0.0,0.0,0.0,1.0,0.0,0
...,...,...,...,...,...,...,...,...,...
595,996,well ran bunch soldiers anf would imagine colo...,neutral,0.0,0.0,0.5,0.0,0.5,0
596,997,pats season,neutral,0.0,0.0,0.0,0.0,0.0,1
597,998,feel every time someone wants hold baby,neutral,0.0,0.0,0.0,0.0,0.0,1
598,999,little name might grow one,neutral,0.0,0.0,0.0,0.0,0.0,1
599,1000,fans patreon rewarded soon,neutral,0.0,0.0,0.0,0.0,0.0,1